### ISSUE TITLE
Linker error: undefined reference to `Diamond::Diamond(Apothesis*)` in apothesis.cpp in the gsoc2023 branch

### ISSUE THREAD

**Issue by PirateOfAndaman** [nixeimar/Apothesis#31]
``/usr/bin/ld: CMakeFiles/apothesis.dir/src/apothesis.cpp.o: in function `Apothesis::init()': `` 
``apothesis.cpp:(.text+0x5f8): undefined reference to `Diamond::Diamond(Apothesis*)'``
`collect2: error: ld returned 1 exit status`
`make[2]: *** [CMakeFiles/apothesis.dir/build.make:593: apothesis] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/apothesis.dir/all] Error 2`
`make: *** [Makefile:91: all] Error 2`

**Comment by PirateOfAndaman** [comment]
@nixeimar PR #33

**Comment by nixeimar** [comment]
Fixed it. Now it compiles as should.
